// automatically generated by the FlatBuffers compiler, do not modify

package com.hfstudio.guidenh.guide.layout.flatbuffers;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

@SuppressWarnings("unused")
public final class ChartData extends Table {

    public static void ValidateVersion() {
        Constants.FLATBUFFERS_23_5_26();
    }

    public static ChartData getRootAsChartData(ByteBuffer _bb) {
        return getRootAsChartData(_bb, new ChartData());
    }

    public static ChartData getRootAsChartData(ByteBuffer _bb, ChartData obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public ChartData __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public float preferredWidth() {
        int o = __offset(4);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float totalHeight() {
        int o = __offset(6);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float chromeHeight() {
        int o = __offset(8);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public static int createChartData(FlatBufferBuilder builder, float preferredWidth, float totalHeight,
        float chromeHeight) {
        builder.startTable(3);
        ChartData.addChromeHeight(builder, chromeHeight);
        ChartData.addTotalHeight(builder, totalHeight);
        ChartData.addPreferredWidth(builder, preferredWidth);
        return ChartData.endChartData(builder);
    }

    public static void startChartData(FlatBufferBuilder builder) {
        builder.startTable(3);
    }

    public static void addPreferredWidth(FlatBufferBuilder builder, float preferredWidth) {
        builder.addFloat(0, preferredWidth, 0.0f);
    }

    public static void addTotalHeight(FlatBufferBuilder builder, float totalHeight) {
        builder.addFloat(1, totalHeight, 0.0f);
    }

    public static void addChromeHeight(FlatBufferBuilder builder, float chromeHeight) {
        builder.addFloat(2, chromeHeight, 0.0f);
    }

    public static int endChartData(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public static final class Vector extends BaseVector {

        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public ChartData get(int j) {
            return get(new ChartData(), j);
        }

        public ChartData get(ChartData obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}
