// automatically generated by the FlatBuffers compiler, do not modify

package com.hfstudio.guidenh.guide.layout.flatbuffers;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

/**
 * Shared gutter marker declaration for a list item.
 * Java writes this field only for a LytListItem that uses a shared marker (ordered "N."
 * with start semantics, unordered U+2022); subclasses with a custom gutter marker (task
 * checkbox and similar) leave it null, which means no marker declaration and no change in
 * behavior.
 *
 * Rust consumption (Rust owns all geometry):
 * * shape `text` through the same shaping pipeline as the body text (parley
 * layout_styled, no line breaking);
 * * vertical baseline = the baseline of the content's first line (the first line of the
 * first content child that has glyph content; see list_marker_pass in layout.rs for the
 * fallback);
 * * horizontal right alignment = the marker's ink right edge lands on the list item's own
 * left edge, which is the document text line of that nesting level (L1=14, L2=24,
 * L3=34); the whole box hangs into the left margin, so no gutter constant is needed;
 * * the marker glyphs join the page-wide output stream as ordinary glyph quads (no new
 * primitive type), with the run color taken from `style.color` (Java declares the gray
 * COL_MARKER).
 * The marker never takes part in line breaking and does not affect the geometry of any
 * content child: content bounds stay byte-for-byte identical.
 */
@SuppressWarnings("unused")
public final class ListMarkerData extends Table {

    public static void ValidateVersion() {
        Constants.FLATBUFFERS_23_5_26();
    }

    public static ListMarkerData getRootAsListMarkerData(ByteBuffer _bb) {
        return getRootAsListMarkerData(_bb, new ListMarkerData());
    }

    public static ListMarkerData getRootAsListMarkerData(ByteBuffer _bb, ListMarkerData obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public ListMarkerData __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    /**
     * Marker text: ordered = "N." (N carries the start value), unordered = U+2022.
     */
    public String text() {
        int o = __offset(4);
        return o != 0 ? __string(o + bb_pos) : null;
    }

    public ByteBuffer textAsByteBuffer() {
        return __vector_as_bytebuffer(4, 1);
    }

    public ByteBuffer textInByteBuffer(ByteBuffer _bb) {
        return __vector_in_bytebuffer(_bb, 4, 1);
    }

    /**
     * Marker style: body font style (BASE_FONT_SIZE 11 / regular), color COL_MARKER gray.
     */
    public com.hfstudio.guidenh.guide.layout.flatbuffers.TextStyle style() {
        return style(new com.hfstudio.guidenh.guide.layout.flatbuffers.TextStyle());
    }

    public com.hfstudio.guidenh.guide.layout.flatbuffers.TextStyle style(
        com.hfstudio.guidenh.guide.layout.flatbuffers.TextStyle obj) {
        int o = __offset(6);
        return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null;
    }

    public static int createListMarkerData(FlatBufferBuilder builder, int textOffset, int styleOffset) {
        builder.startTable(2);
        ListMarkerData.addStyle(builder, styleOffset);
        ListMarkerData.addText(builder, textOffset);
        return ListMarkerData.endListMarkerData(builder);
    }

    public static void startListMarkerData(FlatBufferBuilder builder) {
        builder.startTable(2);
    }

    public static void addText(FlatBufferBuilder builder, int textOffset) {
        builder.addOffset(0, textOffset, 0);
    }

    public static void addStyle(FlatBufferBuilder builder, int styleOffset) {
        builder.addOffset(1, styleOffset, 0);
    }

    public static int endListMarkerData(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public static final class Vector extends BaseVector {

        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public ListMarkerData get(int j) {
            return get(new ListMarkerData(), j);
        }

        public ListMarkerData get(ListMarkerData obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}
