// automatically generated by the FlatBuffers compiler, do not modify

package com.hfstudio.guidenh.guide.layout.flatbuffers;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

@SuppressWarnings("unused")
public final class MediaWikiGeneratedListData extends Table {

    public static void ValidateVersion() {
        Constants.FLATBUFFERS_23_5_26();
    }

    public static MediaWikiGeneratedListData getRootAsMediaWikiGeneratedListData(ByteBuffer _bb) {
        return getRootAsMediaWikiGeneratedListData(_bb, new MediaWikiGeneratedListData());
    }

    public static MediaWikiGeneratedListData getRootAsMediaWikiGeneratedListData(ByteBuffer _bb,
        MediaWikiGeneratedListData obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public MediaWikiGeneratedListData __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public float maxContentHeight() {
        int o = __offset(4);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public static int createMediaWikiGeneratedListData(FlatBufferBuilder builder, float maxContentHeight) {
        builder.startTable(1);
        MediaWikiGeneratedListData.addMaxContentHeight(builder, maxContentHeight);
        return MediaWikiGeneratedListData.endMediaWikiGeneratedListData(builder);
    }

    public static void startMediaWikiGeneratedListData(FlatBufferBuilder builder) {
        builder.startTable(1);
    }

    public static void addMaxContentHeight(FlatBufferBuilder builder, float maxContentHeight) {
        builder.addFloat(0, maxContentHeight, 0.0f);
    }

    public static int endMediaWikiGeneratedListData(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public static final class Vector extends BaseVector {

        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public MediaWikiGeneratedListData get(int j) {
            return get(new MediaWikiGeneratedListData(), j);
        }

        public MediaWikiGeneratedListData get(MediaWikiGeneratedListData obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}
