// automatically generated by the FlatBuffers compiler, do not modify

package com.hfstudio.guidenh.guide.layout.flatbuffers;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

@SuppressWarnings("unused")
public final class MediaWikiSpecialGeneratedData extends Table {

    public static void ValidateVersion() {
        Constants.FLATBUFFERS_23_5_26();
    }

    public static MediaWikiSpecialGeneratedData getRootAsMediaWikiSpecialGeneratedData(ByteBuffer _bb) {
        return getRootAsMediaWikiSpecialGeneratedData(_bb, new MediaWikiSpecialGeneratedData());
    }

    public static MediaWikiSpecialGeneratedData getRootAsMediaWikiSpecialGeneratedData(ByteBuffer _bb,
        MediaWikiSpecialGeneratedData obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public MediaWikiSpecialGeneratedData __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public float maxContentHeight() {
        int o = __offset(4);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public static int createMediaWikiSpecialGeneratedData(FlatBufferBuilder builder, float maxContentHeight) {
        builder.startTable(1);
        MediaWikiSpecialGeneratedData.addMaxContentHeight(builder, maxContentHeight);
        return MediaWikiSpecialGeneratedData.endMediaWikiSpecialGeneratedData(builder);
    }

    public static void startMediaWikiSpecialGeneratedData(FlatBufferBuilder builder) {
        builder.startTable(1);
    }

    public static void addMaxContentHeight(FlatBufferBuilder builder, float maxContentHeight) {
        builder.addFloat(0, maxContentHeight, 0.0f);
    }

    public static int endMediaWikiSpecialGeneratedData(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public static final class Vector extends BaseVector {

        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public MediaWikiSpecialGeneratedData get(int j) {
            return get(new MediaWikiSpecialGeneratedData(), j);
        }

        public MediaWikiSpecialGeneratedData get(MediaWikiSpecialGeneratedData obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}
