// automatically generated by the FlatBuffers compiler, do not modify

package com.hfstudio.guidenh.guide.layout.flatbuffers;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

@SuppressWarnings("unused")
public final class TextData extends Table {

    public static void ValidateVersion() {
        Constants.FLATBUFFERS_23_5_26();
    }

    public static TextData getRootAsTextData(ByteBuffer _bb) {
        return getRootAsTextData(_bb, new TextData());
    }

    public static TextData getRootAsTextData(ByteBuffer _bb, TextData obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public TextData __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public String text() {
        int o = __offset(4);
        return o != 0 ? __string(o + bb_pos) : null;
    }

    public ByteBuffer textAsByteBuffer() {
        return __vector_as_bytebuffer(4, 1);
    }

    public ByteBuffer textInByteBuffer(ByteBuffer _bb) {
        return __vector_in_bytebuffer(_bb, 4, 1);
    }

    public com.hfstudio.guidenh.guide.layout.flatbuffers.TextStyle style() {
        return style(new com.hfstudio.guidenh.guide.layout.flatbuffers.TextStyle());
    }

    public com.hfstudio.guidenh.guide.layout.flatbuffers.TextStyle style(
        com.hfstudio.guidenh.guide.layout.flatbuffers.TextStyle obj) {
        int o = __offset(6);
        return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null;
    }

    public byte whiteSpace() {
        int o = __offset(8);
        return o != 0 ? bb.get(o + bb_pos) : 0;
    }

    public static int createTextData(FlatBufferBuilder builder, int textOffset, int styleOffset, byte whiteSpace) {
        builder.startTable(3);
        TextData.addStyle(builder, styleOffset);
        TextData.addText(builder, textOffset);
        TextData.addWhiteSpace(builder, whiteSpace);
        return TextData.endTextData(builder);
    }

    public static void startTextData(FlatBufferBuilder builder) {
        builder.startTable(3);
    }

    public static void addText(FlatBufferBuilder builder, int textOffset) {
        builder.addOffset(0, textOffset, 0);
    }

    public static void addStyle(FlatBufferBuilder builder, int styleOffset) {
        builder.addOffset(1, styleOffset, 0);
    }

    public static void addWhiteSpace(FlatBufferBuilder builder, byte whiteSpace) {
        builder.addByte(2, whiteSpace, 0);
    }

    public static int endTextData(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public static final class Vector extends BaseVector {

        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public TextData get(int j) {
            return get(new TextData(), j);
        }

        public TextData get(TextData obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}
